Database:
  # [MySQL] (NÃO RECOMENDADO)
  # Tipo: MySQL
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [MySQL + Connection pool (HikariCP)] (RECOMENDADO)
  # Tipo: MySQL-pooling
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [SQLite] (RECOMENDADO)
  # Tipo: SQLite
  # Path:      <Path do arquivo. Ex.: database.sql>
  Tipo: SQLite
  Path: database.sql

# Display do iten do fragmento.
Display-fragmento-fisico:
  Nome: '@nome &7(@quantiax)'
  Lore:
    - '&8Um fragmento físico!'
    - '&7Clique para adicionar'
    - '&7para a sua mochila.'
    - ''
    - '&fB. direito: &7Adicionar'
    - '&fB. direito + SHIFT: &7Juntar'

# Display do iten do limite.
Display-limite-fisico:
  Nome: '&fLimite de @nome &7(@quantiax)'
  Lore:
    - '&8Um limite físico!'
    - '&7Clique para aumentar'
    - '&7o limite do fragmento'
    - '&7na sua mochila.'
    - ''
    - '&fB. direito: &7Adicionar'
    - '&fB. direito + SHIFT: &7Juntar'

# Quando um jogado recêbe fragmentos ou limite *virtualmente* mas não
# tem a capacidade suficiente para armazenar todos, o sistema pode
# compensar o jogador com um iten que contem os fragmentos ou limite que
# que se perder. Use true ou false para ativar ou desativar.
#
# Retirar a opção será aceito como um false.
# OBS: A opção 'Comando' apenas funciona para o comando /rankup darfragmentos ou /rankup darlimite.
Compensacao-fragmentos:
  Comando: true
  Quebrando-blocos: true
  Hitando-mobs: true
  Matando-mobs: true
  Pescando: true

Compensacao-limite:
  Comando: true
  Quebrando-blocos: true
  Hitando-mobs: true
  Matando-mobs: true
  Pescando: true

# Use true ou false para ativar ou desativar opção
# de retiro na /mochila
Retirar-fragmentos: true

# Use false para desativar opção ou a seguinte configuração
# para definir bonus e placeholders
Venda-fragmentos:
  # Usar uma tag proveida pelo grupo de bonus (true) ou não (false)
  Usar-tag: true

  # Tag proveida quando o jogador não pertence a nenhum grupo.
  # Apenas ativa quando a opção 'Usar-tag' estiver ativa
  Sem-bonus: '&cSem grupo'

  # Crie uma lista com grupos que contem permissões que irão receber
  # uma porcentagem de dinheiro adicional na venda de fragmentos.
  # Precisa ter a opção 'Venda-fragmentos' habilitada
  Bonus:
    # Cada grupo segue a seguinte estrutura:
    # Meu-grupo:
    #   Grupo: <grupo_permissao> - O grupo que o jogador deve ter para obter o bonus
    #   Prioridade: <prioridade_de_bonus> - O ordem de leitura dos bonus. Maior o numero, um dos primeiros a ser escolhido
    #   Bonus: <bonus_porcentagem> - O bonus aplicado *em porcentagem*
    #   Tag: <tag_mostrada> - Tag mostrada na venda caso a opção 'Usar-tag' estiver ativada
    Rank-1:
      Grupo: 'rank_1'
      Prioridade: 1
      Bonus: 0.5
      Tag: '&b&lA&bprendiz'
    Rank-2:
      Grupo: 'rank_2'
      Prioridade: 2
      Bonus: 1.25
      Tag: '&5&lM&5ago'
    Rank-3:
      Grupo: 'rank_3'
      Prioridade: 3
      Bonus: 2
      Tag: '&6&lM&6estre'
