Database:
  # [MySQL]
  # Tipo: MySQL
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [MySQL + Connection pool (HikariCP)]
  # Tipo: MySQL-pooling
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [SQLite]
  # Tipo: SQLite
  # Path:      <Path do arquivo. Ex.: database.sql>
  Tipo: SQLite
  Path: database.sql

Display-fragmento-fisico:
  Nome: '@nome &7(@quantiax)'
  Lore:
    - '&8Um fragmento físico!'
    - '&7Clique para adicionar'
    - '&7para a sua mochila.'
    - ''
    - '&fB. direito: &7Adicionar'
    - '&fB. direito + SHIFT: &7Juntar'

Display-limite-fisico:
  Nome: '&fLimite de @nome &7(@quantiax)'
  Lore:
    - '&8Um limite físico!'
    - '&7Clique para aumentar'
    - '&7o limite do fragmento'
    - '&7na sua mochila.'
    - ''
    - '&fB. direito: &7Adicionar'
    - '&fB. direito + SHIFT: &7Juntar'

# Quando um jogado recêbe fragmentos ou limite *virtualmente* mas não
# tem a capacidade suficiente para armazenar todos, o sistema pode
# compensar o jogador com um iten que contem os fragmentos ou limite que
# que se perder. Use true ou false para ativar ou desativar.
# Retirar a opção será aceito como um false
Compensacao-fragmentos:
  Comando: true # Apenas /rankup darfragmentos
  Quebrando-blocos: true
  Hitando-mobs: true
  Matando-mobs: true
  Pescando: true

Compensacao-limite:
  Comando: true # Apenas /rankup darlimite
  Quebrando-blocos: true
  Hitando-mobs: true
  Matando-mobs: true
  Pescando: true