name: WorldRankup
main: com.worldplugins.rankup.WorldRankup
version: 1.0
authors: [PostDev]
api-version: 1.8
depend: [Vault, LuckPerms]
softdepend: [Legendchat, PlaceholderAPI]
commands:
  rankup:
    description: Main command
  mochila:
    description: Shards bag command
  prestigio:
    description: Prestige GUI command
