name: WorldRankup
main: com.worldplugins.rankup.WorldRankup
version: 1.0
authors: [PostDev]
api-version: 1.8
commands:
  rankup:
    description: Main command
  mochila:
    description: Shards bag command
  prestige:
    description: Prestige GUI command
